### ISSUE TITLE
Fix Key Conflict(s)

### ISSUE THREAD

**Issue by jonpas** [eRazeri/CCIP#4]
I have found out that your key is not compatible with mine from JNS Skycranes. The conflict is apparently caused by BIS' bug, as reported here: http://feedback.arma3.com/view.php?id=22133

Renaming either mine or your key fixes the 'conflict', but when trying to make the same key you have with name `CCIP_v0.3a` in Arma 3 Tools it doesn't let me type a dot, so that leads me to some sort of conclusion that your key was made by some older tool that (from what I read on BIS forums) is no longer supported and may cause issues.

Renaming your key to `CCIP_v03a` worked but renaming it to either `CCIP_v0_3a` or `CCIP_v0-3a` didn't work. Apparently using dashes/underscores causes conflicts... I have no idea why or how and apparently BIS doesn't either.

~~Now, I would rename my key from JNS Skycranes, but since I see that dots are not supported at all in the Arma 3 Tools, I would say it's better if it's handled on your side and renamed to `CCIP_v03a` or similar that would work (feel free to send it to me to test before releasing), there might also be issues with other mods but I haven't encountered them yet.~~
After some more testing I found out even weirder conflicts with my key, you can read about it in my comment on linked issue above. I would still suggest making a new key without the dot though, since it's not supported by Arma 3 Tools it probably shouldn't be used, but that's just my assumption.

**Comment by eRazeri** [comment]
Thanks for reporting I'll make a new key then =)

**Comment by jonpas** [comment]
No probs, I will update the one in my mod as well since I found it doesn't work with random others as well. There is some serious weirdness going on on BIS' part though.

Cheers!

**Comment by eRazeri** [comment]
Check it out:
https://github.com/eRazeri/CCIP/releases/tag/v0.4a

Should be okay but as you've investigated it could you confirm if it's fixed.

I use the official tools for making signatures but I use them with my own script to make things a bit easier:
https://github.com/eRazeri/CCIP/blob/master/addons/123_automatic_signer.cmd

**Comment by jonpas** [comment]
New key works perfectly combined with my new key as well, and also my old key. I will be updating mine in the next release as well, it seems we fixed all random encounters, as all those preventing it earlier now work. Good job!

Nice, short and sweet script as well!
